#!/bin/sh

run="$(exists grim && exists wl-copy && exists slurp && echo 1)"

if [ -n "$run" ]; then
	if [ "$1" = "region" ]; then
		grim -g "$(slurp)" - | wl-copy
	else
		grim - | wl-copy
	fi
else
	echo "Can't use agrim"
	exit 1
fi

