#!/bin/sh

set -e

die()
{
    echo "$@"
    exit 1
}

exists grim     || die "Need grim!"
exists wl-copy  || die "Need wl-clipboard!"
exists slurp    || die "Need slurp"
exists jq       || die "Need jq"

if [ "$1" = "region" ]; then
    slurp | grim -g- - | wl-copy
elif [ "$1" = "window" ]; then
    swaymsg -t get_tree | jq -r '.. | select(.focused?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | grim -g- - | wl-copy
else
    grim - | wl-copy
fi
