#!/bin/sh

RPCS3D=$HOME/.config/rpcs3

if [ -d $RPCS3D ]; then
	cd $RPCS3D                   || exit 1
	git add -A                   || exit 0
	git commit -am 'Cron backup' || exit 1
	git push                     || exit 1
else
	echo "RPCS3 dir not found"
	exit 1
fi

exit 0

