#!/bin/sh

case "$PACKAGER" in
	"yay") yay -Sy "$@"
	;;
	"pacman") sudo pacman -Sy "$@"
	;;
	"xbps") sudo xbps-install -S "$@"
	;;
	"apt") sudo apt-get install "$@"
	;;
	"pkg") sudo pkg install "$@"
	;;
	*) echo "get: unknown packager"; exit 1
	;;
esac

