#!/bin/sh

SUDO=$(command -v sudo 2>/dev/null)

case "$PACKAGER" in
	"yay") yay -Syu "$@"
	;;
	"pacman") $SUDO pacman -Syu "$@"
	;;
	"xbps") $SUDO xbps-install -S "$@"
	;;
	"apt") $SUDO apt-get install "$@"
	;;
	"pkg") $SUDO pkg install "$@"
	;;
	*) echo "get: unknown packager"; exit 1
	;;
esac

