#!/bin/sh

HA_PROXY_LIST="                                                       \
XN-XSVM-S-4-LDP12-GB                                                  \
XN-XSVM-S-52-LDP12-GB                                                 \
XN-XSVM-S-69-LDP12-GB                                                 \
"

for p in $HA_PROXY_LIST; do
    /Applications/iTerm.app/Contents/MacOS/iTerm2:
