#!/bin/sh

if [ "$PKGR" = "pacman" ]; then
    pacman -Qett --color=auto | $PAGER
elif [ "$PKGR" = "xbps" ]; then
    xbps-query -m | $PAGER
elif [ "$PKGR" = "apt" ]; then
    apt list --installed
fi
