#!/bin/sh

if [ "$PACKAGER" = "pacman" ]; then
    pacman -Qett --color=auto | $PAGER
elif [ "$PACKAGER" = "xbps" ]; then
    xbps-query -m | $PAGER
elif [ "$PACKAGER" = "apt" ]; then
    apt list --installed
fi
