#!/bin/sh

case "$PKGR" in
    "yay") pacman -Ss "$@"
    ;;
    "pacman") pacman -Ss "$@"
    ;;
    "xbps") xbps-query --regex -Rs "$@"
    ;;
    "apt") apt-cache search --names-only "$@"
    ;;
    "pkg") pkg search "$@"
    ;;
    *) echo "get: unknown packager"; exit 1
    ;;
esac
